adminUser:
  password: vault:neckcyan/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:neckcyan/pipelineUser:token
  username: cloudbees-ci-cd[bot]
prow:
  hmacToken: vault:neckcyan/prow:hmacToken
segmentWriteKey: vault:neckcyan:segmentWriteKey
